/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://2vnkx65esnerdbstzpl7cqkcbu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-lubmqgirxvhgdjal3f2r4q36c4",
    "aws_cognito_identity_pool_id": "us-east-1:f8e53b33-0ec6-4de4-81da-015f6154aca5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sSiVhzaKL",
    "aws_user_pools_web_client_id": "5f04ccf3lg42eig7qe9olv11gs",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "client1680096a403f4915970a0724b0341d03677cc-main",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
